### ISSUE TITLE
cannot load such file - ruby 3.0 - windows

### ISSUE THREAD

**Issue by bgmat** [net-ssh/bcrypt_pbkdf-ruby#20]
How to reproduce:
1. Create a new rails app: rails new app_name
2. add the following gems in the Gemfile:
gem 'net-sftp', '~>4.0.0'
gem 'ed25519', '~>1.2.0'
gem 'bcrypt_pbkdf', '~>1.1.0'
3. bundle
4. rails c

The output:
C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- bcrypt_pbkdf_ext (LoadError)
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `block in require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:299:in `load_dependency'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bcrypt_pbkdf-1.1.0-x64-mingw32/lib/bcrypt_pbkdf.rb:5:in `rescue in <main>'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bcrypt_pbkdf-1.1.0-x64-mingw32/lib/bcrypt_pbkdf.rb:1:in `<main>'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler/runtime.rb:55:in `each'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler/runtime.rb:55:in `block in require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler/runtime.rb:44:in `each'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler/runtime.rb:44:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler.rb:176:in `require'
        from C:/Temp/test-gem/config/application.rb:7:in `<main>'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/command/actions.rb:22:in `require_application!'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/commands/console/console_command.rb:101:in `perform'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- 3.0/bcrypt_pbkdf_ext (LoadError)
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `block in require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:299:in `load_dependency'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bcrypt_pbkdf-1.1.0-x64-mingw32/lib/bcrypt_pbkdf.rb:3:in `<main>'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler/runtime.rb:55:in `each'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler/runtime.rb:55:in `block in require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler/runtime.rb:44:in `each'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler/runtime.rb:44:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bundler-2.3.3/lib/bundler.rb:176:in `require'
        from C:/Temp/test-gem/config/application.rb:7:in `<main>'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/command/actions.rb:22:in `require_application!'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/commands/console/console_command.rb:101:in `perform'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from C:/Ruby/3.0.5-1/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
---------------------------------------------------------------------------------------------------------------

The gem does not build the "bcrypt_pbkdf_ext.so" file for ruby 3.0.
Any idea how to do this?

**Comment by RingLcy** [comment]
for gem:       gem install bcrypt_pbkdf --platform=ruby
for bundle:   bundle config set --local force_ruby_platform true
As a result, gem with native extensions will be compiled from source.

**Comment by mfazekas** [comment]
We should be now precompile for 3.0.0 for windows

https://github.com/net-ssh/bcrypt_pbkdf-ruby/blob/4a159658b11b330166de02dd9d51ca820931ae98/Rakefile#L12-L19
